/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dist_pipe.h"

CLIENT* get_clnt(char* host) {
	CLIENT *clnt = clnt_create (host, DIST_PIPE, beta, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	return clnt;
}

int put(char* host, char* payload, int close) {
	CLIENT *clnt = get_clnt(host);
	msg message;

	message.data = payload;
	message.status = close ? END : OK;

	int  *result = pipe_put_101(message, clnt);
	clnt_destroy (clnt);
	
	return *result;
}

msg* get(char* host) {
	CLIENT *clnt = get_clnt(host);
	msg *result = pipe_get_101(clnt);
	
	clnt_destroy (clnt);
	return result;
}



int main (int argc, char *argv[]) {
// USAGE: ./dist_pipe_client put <message> <close(true/false)>
//		  ./dist_pipe_client get

	char *host = "localhost";

	if (strcmp(argv[1], "get") == 0) {
		msg* m = get(host);
		switch(m->status) {
			case OK: {
				printf("got message: %s\n", m->data);
				break;
			}
			case EMPTY: {
				printf("pipe is empty\n");
				break;
			}
			case END: {
				printf("pipe is closed\n");
				break;
			}
		}
	} else if (strcmp(argv[1], "put") == 0) {
		int result;
		if (strcmp(argv[3], "true") == 0)
			result = put(host, argv[2], 1);
		else
			result = put(host, argv[2], 0);

		switch(result) {
			case OK: {
				printf("message sent\n");
				break;
			}
			case FULL: {
				printf("pipe is full\n");
				break;
			}
			case FINISHING: {
				printf("pipe is closed already\n");
			}
		}
	}
	

exit (0);
}
