/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dist_pipe.h"


void
dist_pipe_101(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	message_v pipe_put_101_arg1 = "arg";
	message_v  *result_2;

#ifndef	DEBUG
	clnt = clnt_create (host, DIST_PIPE, alfa, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = pipe_put_101(pipe_put_101_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = pipe_get_101(clnt);
	if (result_2 == (message_v *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("%s\n", *result_2);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	dist_pipe_101 (host);
exit (0);
}
