/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dist_pipe.h"
#define buffer_size 3

static char* buffer[buffer_size] = {NULL};

int read_pos = 0;
int write_pos = 0;

int end = 0;

int *
pipe_put_101_svc(msg arg1,  struct svc_req *rqstp)
{
	static int  result;
	if (buffer[write_pos] == NULL) {
		end = (arg1.status == END) ? 1 : 0;

		int data_len = strlen(arg1.data);

		buffer[write_pos] = malloc(data_len * sizeof(char) + 1);
		strncpy(buffer[write_pos], arg1.data, data_len);
		buffer[write_pos][data_len] = '\0';

		write_pos = (write_pos + 1) % buffer_size;

		result = OK;
	} else {
		result = FULL;
	}

	return &result;
}

msg *
pipe_get_101_svc(struct svc_req *rqstp)
{
	static msg result;
	
	if (buffer[read_pos] == NULL) {
		result.data = "";
		result.status = end ? END : EMPTY;
	} else {
		result.data = buffer[read_pos];
		result.status = OK;
		buffer[read_pos] = NULL;
		read_pos = (read_pos + 1) % buffer_size;
	}

	return &result;
}
