/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DIST_PIPE_H_RPCGEN
#define _DIST_PIPE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *message_v;

#define DIST_PIPE 0x20000001
#define alfa 101

#if defined(__STDC__) || defined(__cplusplus)
#define pipe_put 1
extern  int * pipe_put_101(message_v , CLIENT *);
extern  int * pipe_put_101_svc(message_v , struct svc_req *);
#define pipe_get 2
extern  message_v * pipe_get_101(CLIENT *);
extern  message_v * pipe_get_101_svc(struct svc_req *);
extern int dist_pipe_101_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define pipe_put 1
extern  int * pipe_put_101();
extern  int * pipe_put_101_svc();
#define pipe_get 2
extern  message_v * pipe_get_101();
extern  message_v * pipe_get_101_svc();
extern int dist_pipe_101_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message_v (XDR *, message_v*);

#else /* K&R C */
extern bool_t xdr_message_v ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DIST_PIPE_H_RPCGEN */
